# dhcpd.conf - TechKaram GmbH

option domain-name "karam.local";
option domain-name-servers 192.168.10.10;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

# VLAN10 - IT Department subnet
subnet 192.168.10.0 netmask 255.255.255.0 {
  range dynamic-bootp 192.168.10.50 192.168.10.100;
  option routers 192.168.10.10;
  option domain-name-servers 192.168.10.10;
}
