# Samba Configuration - TechKaram GmbH

[it-share]
path = /mnt/raid/it
browseable = yes
read only = no
valid users = @it
create mask = 0770
directory mask = 0770

[development-share]
path = /mnt/raid/development
browseable = yes
read only = no
valid users = @development @it
create mask = 0770
directory mask = 0770

[accounting-share]
path = /mnt/raid/accounting
browseable = yes
read only = no
valid users = @accounting @it
create mask = 0770
directory mask = 0770

[management-share]
path = /mnt/raid/management
browseable = yes
read only = no
valid users = @management @it
create mask = 0770
directory mask = 0770

[sales-share]
path = /mnt/raid/sales
browseable = yes
read only = no
valid users = @sales @it
create mask = 0770
directory mask = 0770
